### ISSUE TITLE
baro behaving strangely with x-touch mini in Cessna 172

### ISSUE THREAD

**Issue by slimjimsim** [markcellis/X-KeyPad#100]
I am having trouble controlling the baro with the x-touch mini. I tried using the commands.
"Clockwise Command Name": "sim/instruments/barometer_up",
"Counterclockwise Command Name": "sim/instruments/barometer_down",

The current result is that turning the dial _either_ way results in a -20HPa decrease in the baro setting. 
I have also loaded in the sample C172 script which seems to use a different dataref based technique? This results in the baro dropping to around 920 with the first turn and then nothing further. Pressing the button does set the baro to standard 1013 though.

Any ideas? Thanks.

**Comment by slimjimsim** [comment]
Forgot to say, I have upgraded to 1.6.0.

**Comment by markcellis** [comment]
Do you have the older C172 X-Keys sample loaded and running? This is for Virtual Devices. I’m not talking about the X-Touch VD label sample.

 

That older C172 VD sample had some funky formula for handing the BARO which could interfere. I fixed the sample in 1.6.0 but if you have that old one loaded it could be causing issues.

 

Mark

**Comment by slimjimsim** [comment]
Hi. Thanks for your reply. I was using the sample that came with the 1.6.0 release. Looks like it was created on 11th June 2023. 
The good news is, I removed the json files and started from scratch using the plugin config and this time the commands are now working! That is;
"Clockwise Command Name": "sim/instruments/barometer_up",
"Counterclockwise Command Name": "sim/instruments/barometer_down",

Thanks, Jim.
