### ISSUE TITLE
Button that sorts all keys and/or encoders

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#102]
This is a quality of life request, so no high priority at all.
I'd love to be able to sort all the keys and encoders with a simple press of a button instead of dragging 300+ keys around.

I use `pf.<aircraft/plugin>.<key_type>.<name>` (`pf` for Passenger Flying, the name I use for my work) as a naming convention now, so sorting would help navigating all the keys a lot.

**Comment by markcellis** [comment]
This will be in 1.6.1 beta 2
