### ISSUE TITLE
Show result of expression next to SOURCE button

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#105]
![SCR-202407191243-gXE33aGa](https://github.com/user-attachments/assets/c979f7ac-3791-4078-8f5c-d02d2def6be0)

You already show the result of the logic dataref in the left column. But when changing the source (to another dataref or an expression) the result is only visible when pressing the source button. I'd love to be able to see it in this overview as well.

**Comment by sanderdatema** [comment]
I just noticed the `Last Test:` item, but it never shows anything.

**Comment by markcellis** [comment]
That is odd. The first value in the Last Test (Source Val:Compare Val) should be the value of the data source.

**Comment by markcellis** [comment]
This fix will be available in 1.6.1 Beta 3
