### ISSUE TITLE
UserGuide: Add Bookmarks & Chapter Numbering

### ISSUE THREAD

**Issue by GladYouAsked** [markcellis/X-KeyPad#107]
Hello Mark,

the user guide is really a good source for information. Thanks for providing such a comprehensive document!

Really a minor issue and just a proposal:

1. Could you add chapter headings as bookmarks to the user guide?
This would improve navigation in the document, as you can show the bookmarks in the navigation panel in the PDF reader.
(at least I see no bookmarks in Foxit PDF-reader and in Brave).

2. Could you add chapter numbers to the headings?
I typically scroll back and forth through the manual, and I remember quite well the sections/numbers I often use.
But without chapter numbers you do not know if you should scroll up or down.

Thank you & best regards

**Comment by markcellis** [comment]
I use an older version of Microsoft Word to create the User Guide and then I just save it as a PDF. Do you know what I need to add to the Word doc to get these PDF bookmarks? I'll attach the Word Doc so maybe you can play with it and tell me what I need to do.
[Manual.docx](https://github.com/user-attachments/files/16323870/Manual.docx)

**Comment by GladYouAsked** [comment]
Hello Mark, 
thank you very much for the manual!

**For the bookmarks:**

In Word, 
- click the File tab and click "Save As"
- Select "*.pdf" from the "Save as" type drop-down list
- Click Options and set "Create bookmarks using: Headings"
- Click Save.

I hope this works in your older version of Word as well. 

This is how it looks in the PDF-Reader (much easier to navigate in the document):

![Bookmarks](https://github.com/user-attachments/assets/02439b44-a77e-468e-a392-62367bb6d51c)

**For the chapter numbering:**

I have added the word-file with chapter numbering.
But I have to agree this numbering may be a personal preference. The bookmarks already help a lot to identify the main chapters and to navigate inside the document.

[X-KeyPadManual_inclChapterNumbers.docx](https://github.com/user-attachments/files/16325262/X-KeyPadManual_inclChapterNumbers.docx)

**Comment by markcellis** [comment]
This will be in the PDF as of 1.6.1 Beta 3
