### ISSUE TITLE
Cannot enter the number 10 for a FormulaFloat in a key label line segment.

### ISSUE THREAD

**Issue by RangerGH** [markcellis/X-KeyPad#109]
I found a weird issue.  I have eleven float formulas 0-10.  When I use formula 10 in a key label expression I can not enter a 10 in the array index.  I can enter 0-9 and 11-99 but not 10. When I enter 10 it reverts to 9.
[1:29 AM]
Looking at the Formula float dataref array in the finders window and showing detail shows 10 has the expected value and there are no errors on the formula

I can enter the number 10 just fine in VSCode so the keyboard is working.

**Comment by markcellis** [comment]
I'm not sure I know where in the UI you are. The dataref, SRS/X-KeyPad/FormulaFloat, should always show an available index of 0 - 99. See attached image.

![Capture](https://github.com/user-attachments/assets/529f818c-7dd4-4f29-9566-3d2b8654d35d)

It might be helpful if you zipped up and attached your configuration and also show me which key and label section where this is not working.

**Comment by RangerGH** [comment]
I will do that.  I should have done that last night.

**Comment by RangerGH** [comment]
I’m attaching my config and a screenshot of the key label I’m working with.  It says 0-99 but if I enter 10 it drops back to 9.  My keyboard is working because I tested that on VSCode.

**Comment by RangerGH** [comment]
Ignore the previous zip.  Use this one.

**Comment by RangerGH** [comment]
On that same key label I tried entering a 10 in another line segment and it did the same – went to a 9.

**Comment by markcellis** [comment]
I don't see the zip attachment. It could be GitHub blocks those. Can you send the zip to me via a DM on X-Plane.org.  My username is markcellis.

Thanks

**Comment by RangerGH** [comment]
Will do.

**Comment by RangerGH** [comment]
Done.

**Comment by markcellis** [comment]
I sent you a DM on X-Plane.org with a fix to try. Please let me know if it works. This was a nasty bug, thanks for finding it.

**Comment by RangerGH** [comment]
I will do that this evening and let you know.

**Comment by markcellis** [comment]
This was fixed in 1.6.1 Beta 3

**Comment by RangerGH** [comment]
Excellent.
