### ISSUE TITLE
The clear option should ask for confirmation

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#110]
![SCR-202407212243-ejc2CtY3](https://github.com/user-attachments/assets/1c671b82-ffd3-4c34-9d93-59fc31cec338)
When pressing clear the whole profile is erased without confirmation. I just lost the last 5 minutes of work because I miss clicked. I wanted to choose append, but clicked clear.

It would be nice to have a confirmation first.

**Comment by markcellis** [comment]
Per our Discord discussion, this was satisfied by saving a copy of the configuration to the AutoSave folder before doing the File-Clear. This will be available in 1.6.1 Beta 3
