### ISSUE TITLE
Non integer increment

### ISSUE THREAD

**Issue by florincoter** [markcellis/X-KeyPad#112]
Please, please, add non integer increment. I cannot make it the other way.
And its only natural, IMHO.

Thank you,
Florin.

**Comment by markcellis** [comment]
This is not too difficult on the Stream Deck and possibly the X-Touch mini but it is more complicated with the X-Keys devices and Virtual Devices. Which did you need this for?

**Comment by markcellis** [comment]
This does not look too difficult to do. I'll give it a try

**Comment by florincoter** [comment]
Hi Mark,

 

Thank you a lot! I need it for the Virtual Devices.

 

F.

 

 

Dr. Florin Coter

9A Baal Shem Tov St., Haifa 3372427, ISRAEL

Cell.: +972 (54) 4FLORIN

Web:  <http://www.florincoter.wix.com/fcph> www.florincoter.wix.com/fcph

 

"When you feel the breeze on your cheek, you know that is God. When there is no breeze, you should run." (A Buddhist Monk)

"Don't practice untill you get it right. Practice until you cannot get it wrong." (Unknown)

**Comment by markcellis** [comment]
This will be in 1.6.1 Beta 4

**Comment by florincoter** [comment]
11 thumbs up!

 

Dr. Florin Coter

9A Baal Shem Tov St., Haifa 3372427, ISRAEL

Cell.: +972 (54) 4FLORIN

Web:  <http://www.florincoter.wix.com/fcph> www.florincoter.wix.com/fcph

 

"When you feel the breeze on your cheek, you know that is God. When there is no breeze, you should run." (A Buddhist Monk)

"Don't practice untill you get it right. Practice until you cannot get it wrong." (Unknown)
