### ISSUE TITLE
All clear buttons should have a confirmation

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#116]
Yes, it's probably me. 😀 But I find myself clicking the clear button (instead of the buttons next to it, the paste button for example comes to mind) far too often to my liking. And since there is no undo, I might loose quite a lot of work that was done since the last (auto)save.

So please, add some kind of confirmation, make them harder to click, anything. 😀 
And yes, I mean ALL clear buttons.

**Comment by markcellis** [comment]
Here is one thought.

When you click the clear button it will change to a Confirm button. You must click that in 5 seconds to actually do a clear. If you don't click it in 5 seconds it will revert back to a clear button.

Thoughts?.....

**Comment by sanderdatema** [comment]
Yes, beautiful!

Op do 15 aug 2024, om 14:55 schreef Mark Ellis:

**Comment by markcellis** [comment]
This will be available in 1.6.1 Beta 6
