### ISSUE TITLE
Can't delete conditions on 1.6.1B6

### ISSUE THREAD

**Issue by ribenn** [markcellis/X-KeyPad#120]
I am using X-KeyPad_1.6.1Beta6.
In the X-Keypad Configuration Editor, under the Font Colors and Key Colors / Background tabs, I tried to delete couple of conditions I am not using under both tabs and discovered by clicking on the Trash Can icon, it will not delete.  Nothing happens.  In fact, none of them will delete.

I went under the Key Label tab and the Complex Line Editor and was able to delete a line there. The OK box does appear.  The only way to clear the conditions was to use the Revert button to go back to the previous saved config.

I went back and reinstalled Beta 5.  It all works fine.  I re-downloaded Beta 6 again and tried it - same issue.  Is this a Beta 6 issue?

**Comment by markcellis** [comment]
I have the problem reproduces, I'll fix it

**Comment by markcellis** [comment]
This is a problem with all conditions under numeric speech, font colors, key / background colors, and key labels when there is more than one condition. I see this also extends to the streamdeck configuration editor. I suspect anything to do with multiple conditions.

**Comment by ribenn** [comment]
Thank you very much for checking.
ribenn

**Comment by markcellis** [comment]
This is fixed in 1.6.1 Beta 7

**Comment by ribenn** [comment]
Thanks, it is working now.
