### ISSUE TITLE
importing sample virtual keypad freezes cowl flap controls on laminar B58

### ISSUE THREAD

**Issue by fwiw99** [markcellis/X-KeyPad#124]
- I am trying to set up a virtual keypad for the Laminar B58 Baron
- when I set up xtouch 1 and xtouch 2, the cowl flap controls work at each point.  
- however,  when I import an x-keypad 1.6 sample JSON virtual unit, the cowl flap controls freeze and cannot be moved - neither via mouse nor via xkey assignment
- only plugin is x-keypad

xp 12.1.2
xkeypad 1.6
log 1: - successively add xtouch 1 and x-touch 2- cowl flap controls work at each point
log 2- now add add xk80 virtual unit json from xkeypad 1.6 samples- cowl flap controls no longer work

Device name	DESKTOP-D9U40RV
Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	F579EEA4-217E-45D9-821C-E7B3FED813FF
Product ID	00325-81640-71061-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	23H2
Installed on	‎4/‎3/‎2023
OS build	22631.4460
Experience	Windows Feature Experience Pack 1000.22700.1047.0

[X-KeyPad_Baron_58.zip](https://github.com/user-attachments/files/18054559/X-KeyPad_Baron_58.zip)
[Log 1 load xtouch 1 and xtouch 2.txt](https://github.com/user-attachments/files/18054568/Log.1.load.xtouch.1.and.xtouch.2.txt)
[Log 2 load sample be58 xk80 keypad.txt](https://github.com/user-attachments/files/18054569/Log.2.load.sample.be58.xk80.keypad.txt)

**Comment by markcellis** [comment]
That is the expected behavior. The reason for that is that the sliders are always sending current data to the datarefs as they have no event associated with them. They act almost like a joystick axis.

Another way to do this is to use the rotary encoders.

**Comment by fwiw99** [comment]
Many thanks - sorry to have bothered you.

Best,
- Eric
