### ISSUE TITLE
X-KeyPad 1.5.1-b5 + XP12 = no speech

### ISSUE THREAD

**Issue by CyberGuerro** [markcellis/X-KeyPad#25]
As in subject, in XP12 the speech is lost, probably due the new audio system (FMOD)
This happen on Linux platform, I don't know if it's present on other platforms

**Comment by markcellis** [comment]
Actually, X-Plane never supported Text to Speech on Linux for either X-Plane 11 or X-Plane 12. On X-Plane 12 they are doing something funky with ATC where they stitch together a bunch of individual audio files but it is not using any text-to-speech engine.

I should probably give you a warning if you try to define command speech on Linux.

**Comment by CyberGuerro** [comment]
With XP11 I used [XLinSpeak](https://github.com/uglyDwarf/x-plane_plugins/tree/master/XLinSpeak) (it use Speech-dispatcher to make TTS) with yours and x-Keypad speak.Now with XP12 I rebuilt XLinSpeak with last LR SDK for using with XP12 but X-KeyPad doesn't speak anymore. I don't know if you have to do something within your code.

**Comment by markcellis** [comment]
Can you see if X-KeyPad 1.5 will work with XLinSpeak and XP-12? You will get some warnings about deprecated datarefs but it will run. I suspect Laminar did something in the new SDK that might be affecting this. Let me know what you find.

By the way, all I'm doing is calling XPLMSpeakString. 

Mark

**Comment by CyberGuerro** [comment]
I loaded 2 plugins both and no error in log (only deprecated daterefs in x-keypad). I don't know if the issue is in x-keypad or xLinSpeak plugin.
I don't know what to do again...   ...I'm non C++ programmer. Can I ask you (if you have time and you want) to check/investigate (I think that xLinkSpeak developer would be happy to help to solve the issue if it depend by its plugin).

PS.
I tested xLinSpeak with [Xchecklist](https://forums.x-plane.org/index.php?/files/file/20785-xchecklist-linwinmac/) and Xchecklist works great (I can hear all list calls, I couldn't hear until I recompiled xLinSpeak for XP12), so I don't think that problem is in xLinSpeak

**Comment by markcellis** [comment]
One other thing to check is to make sure you don't have text-to-speech shut off in X-KeyPad. I'm talking to Sparker about how it works. If it works with XCheckList I would think it would work with X-KeyPad.

![image](https://user-images.githubusercontent.com/25938986/208293395-22e3e2db-3a8c-413a-a104-eedf69d29413.png)

**Comment by CyberGuerro** [comment]
It was the first check I did :-)

**Comment by markcellis** [comment]
Ok, I spoke to Sparker, and here is the deal. The reason XCheckList works is it never used XPLMSpeakString, he calls a native Linux Text to Speech function so XLinSpeak is not required for XCheckList.

He is trying to get XLinSpeak working on XP12 but is having some challenges. Probably explains why you are having difficulty too.

**Comment by CyberGuerro** [comment]
Well, if you adopt the same approach of xCheckList for linux version of X-KeyPad?  in this case I can suppose to dismiss xLinSpeak reducing the number of plugins and resources used by X-Plane.
At the moment I was supposing to use xLinkSpeak for WorldTraffic (it doesn't speak now and developer is migrating to FMOD for his ATC), xCheckList (that you told me it doesn't use xLinSpeak) and your plugin.
I conclusion if you solve the issue without xLinSpeak I can definitively dismiss xLinSpeak.

PS. in linux I've installed speech-dispatcher to make TTS.

**Comment by markcellis** [comment]
I may take a look at speech-dispatcher. I wonder if I can count on it being installed on all Linux Distros.

**Comment by markcellis** [comment]
This will be in 1.5.1 beta 7

**Comment by markcellis** [comment]
Fixed in Beta 7
