### ISSUE TITLE
Support a simple horizontal or vertical progress bar on a key

### ISSUE THREAD

**Issue by markcellis** [markcellis/X-KeyPad#30]
Support a simple horizontal or vertical progress bar on a key based on a min-max range on a dataref

**Comment by Bluesscale** [comment]
Hi Mark, I'm thinking of possible changes for consideration.  These relate to the Virtual Keypad.  The first is to have work saved on the fly without having to press the SAVE key.  When working with the Complex Line Editor....when adding a line or adding a line segment have the cursor go to the radio button of that line.  The most common thing to do is add a line and edit it right away.  
I'm not sure if this is a bug but sometimes a Complex Line becomes changed to a non-complex line.  For example, a line with arrows in the complex line will revert to B & A in an ordinary Label Text.  I haven't noticed a pattern of this occurring.

**Comment by markcellis** [comment]
I'll add those as separate issues when I get around to working on this one.

**Comment by markcellis** [comment]
Completed and will be in 1.5.1 Beta 30. Only supports horizontal progress bars as they are associated with a line on the label.
