### ISSUE TITLE
Feature request for X-Touch mini

### ISSUE THREAD

**Issue by MFD529** [markcellis/X-KeyPad#33]
Many Thranda aircraft have a feature where one of their menu buttons supports several DR items. For example in their custom side menu to Remove All Tie downs there are 4 individual DR values assigned to this one menu button. Could you support a single button press to support more than one single data ref? Another item in their menu is called All Covers which is assigned to the Intake and Pitot cover.

Thanks for the great software for the X-Touch Mini. I'm anxiously awaiting what your magic can bring to the Elgato StreamDeck ;-) Mike D

**Comment by markcellis** [comment]
The ability to run multiple commands on a single button press will be in the very next beta. You already have the ability to use slave datarefs, will that work?

**Comment by MFD529** [comment]
I didn't even think of using the Slaves ;-)Thanks for the tip and I'll give that a quick go!

**Comment by MFD529** [comment]
Slave data ref feature worked perfect. Now why didn’t I think of that?? :-)

Sent from my iPhone

On Jan 25, 2023, at 11:00 AM, Mark Ellis ***@***.***> wrote:

﻿

The ability to run multiple commands on a single button press will be in the very next beta. You already have the ability to use slave datarefs, will that work?
