### ISSUE TITLE
Enhancement Request - Assign a Key to a Unit

### ISSUE THREAD

**Issue by ssharpe83713** [markcellis/X-KeyPad#36]
We can step through units with Virtual_Device_Previous_Unit and Virtual_Device_Next_Unit, but I'd like to assign a Unit to a key so that I can jump to the Unit directly (as an alternative to touching the unit reference at the top of the screen).  I would be particularly helpful when the desired result would be a shifted Unit when the starting Unit was unshifted....one key press versus two.

**Comment by markcellis** [comment]
I can probably implement this similarly to what we did in X-Camera by assigning the unit shifted and unshifted states to a display ID. We can then have commands like Select_Display_ID_n where n is the display id number.

**Comment by markcellis** [comment]
This will be available in 1.5.1 Beta 33. You can use the enhanced behavior of the dataref, **Virtual_Device_Selected_Unit**, using either a numeric dataref set function or the new expressive command to set the unit and shift state on a specific virtual device.
