### ISSUE TITLE
command and numeric speech

### ISSUE THREAD

**Issue by GeraldJohn** [markcellis/X-KeyPad#37]
There is a problem with the use of speech feature. On my Linux computer the current local language is German. That means the  Numeric and Command speech on Linux using spd-say does use German as DefaultLanguage thoughI uncommented  DefaultLanguage "en-US" in the speechd.conf . The corresponding comment in speechd.conf says 

       Note that the spd-say client in particular always sets the language to its
       current locale language, so this particular client will never pick this configuration.

Is it possible to get the funtion of the command line call like "spd-say --language=en..." to be used with X-KeyPad or any other way to get around this.
Maybe its a configuration point in X-Plane itself.
Gerald

**Comment by markcellis** [comment]
This is complete and will be released in 1.5.1 Beta 30

**Comment by GeraldJohn** [comment]
I am glad that they were able to solve the problem. Unfortunately I can try the new version in 10 days due to professional absence
