### ISSUE TITLE
Keypad numbers displayed on monitor using Streamdeck

### ISSUE THREAD

**Issue by MFD529** [markcellis/X-KeyPad#39]
When I enter keypad values via SD I see them displayed on main monitor. I also noticed that in your demo video. 
![KEYPAD](https://user-images.githubusercontent.com/115599754/224489112-36f60670-9687-4cfa-a3ad-c4f82d716057.JPG)

**Comment by markcellis** [comment]
This is by design, you can shut it off with this setting:

![image](https://user-images.githubusercontent.com/25938986/224510126-b820a9c7-2aa0-4643-974e-f76510d74e6d.png)

Mark

**Comment by MFD529** [comment]
Thanks for the feature 🙂

Mike
________________________________

**Comment by markcellis** [comment]
Answered
