### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MFD529** [markcellis/X-KeyPad#42]
Mark as the definition list gets longer could you anchor the area within yellow so it doesn't scroll out of view? I'm about 75 key definitions deep so far and I would find it handy to always have the tabbed area in view and quick to go to.  Thanks for a great add-on feature for Streamdeck ;-) Mike
![Feature request](https://user-images.githubusercontent.com/115599754/225945135-7f694f56-e4a4-4033-9f0f-a0acfeb58955.JPG)

**Comment by markcellis** [comment]
This is complete and will be in Beta 17
