### ISSUE TITLE
Request: treat dialPress on SD+ as any other key (when not part of multi encoder)

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#45]
Comparable to the way the encoders work on the X-Touch Mini. We are able to program both short and long presses there unless the encoder is programmed to do multiple things, in which case the short (or long press) event is reserved.

Maybe even a setting to choose between short and long presses to switch between multi encoders. Because now the SD+ uses a short press and the X-Touch mini uses long presses.

**Comment by markcellis** [comment]
Do you still think this is necessary now that we have the tap touch? That gives you two actions on the encoder in both single and multi-encoder modes.

**Comment by sanderdatema** [comment]
Well, it would still be nice to have long presses as well. Specially for Airbusses. The touchTap would be to switch between modes (HDG vs TRK for example), short pressing the encoder would be push and long press pull.

**Comment by markcellis** [comment]
This is complete and will be available in 1.5.1 Beta 25
