### ISSUE TITLE
Request: Option to have an SD key blink

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#51]
At the moment you can have a key show a background image and/or lines of text when certain conditions are met.

**Current situation**
Example: when logic test is true, show red background and text "Warning".

**Proposal**
Same example: When logic test is true, switch between two backgrounds at a set interval and 

For this you would need an extra setting for both Background Image and Lines. And to be able to set the interval at which we switch between those two.

I hope my explanation is clear. 😀 In the end it would look as if a key is blinking, using two images and/or different texts (and maybe even colors).

**Comment by markcellis** [comment]
This will be available in 1.5.1 Beta 21.

Note: I did not do flashing lines as the line code is shared between Stream Deck and Virtual devices. I'm also going to make the flash flag available as a dataref so if you really needed it you could do it with that dataref. The dataref name is:

SRS/X-KeyPad/LedBlinkState
