### ISSUE TITLE
Bug: layouts reset (and not sent again) when encoder name is changed

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#54]
Steps to reproduce:
- name encoder test1
- create custom layout, add some lines and update stream deck
- rename encoder
- set new encoder name in property inspector of stream deck
- stream deck will revert back to default layout
- press `update stream deck` in plugin. Nothing happens.
- edit part of the layout, update. Will work now.

**Comment by markcellis** [comment]
I think I have this fixed and it will be available in 1.5.1 Beta 24
