### ISSUE TITLE
Bug: touchTap not always registered

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#55]
I checked to be sure: my SD+ works fine, touchTaps are registered. But X-KeyPad seems to be missing some of them.
Is there a way to debug this? Like logging each press?

**Comment by markcellis** [comment]
Does it happen only with specific commands and is it consistently broken with those commands?

**Comment by sanderdatema** [comment]
It seems to be command dependent. The ToLiss Airbus commands in this case (HDG, SPD and ALT) have trouble registering.

**Comment by markcellis** [comment]
This is fixed and will be available in 1.5.1 Beta 24
