### ISSUE TITLE
Bug: Setting Complex Line Editor is sometimes not saved

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#56]
I'm afraid I don't know how to reproduce this. But I'll report it anyway.

I noticed that between restarts of X-Plane some encoders (I haven't seen it with keys yet) where I enabled the `Complex Line Editor`, that checkbox is no longer selected and instead it's a normal text box, but with the values I did program before.

I noticed it happens when all the lines I added are of type text. But for the SD+ layouts it's important to keep the Complex Line Editor.

**Comment by markcellis** [comment]
I'm pretty sure the way that works is if all lines are just text and there is only one line segment per line it assumes it is not complex and you just get the multi-line text editor field.  Why does it need to stay complex? Maybe there is another bug where blank starting or trailing lines are getting trimmed somehow.

**Comment by markcellis** [comment]
This is the way it works when lines only have one segment and all the segments are text segments. The multi-line edit widget is the default edit method in this condition.
