### ISSUE TITLE
Feature Request for SD - flashing folder background image

### ISSUE THREAD

**Issue by MFD529** [markcellis/X-KeyPad#57]
Mark - would it possible to support the following behavior on SD, a folder, let's call it Circuit Breakers. Inside that folder of course would be a handful of circuit breakers. Now my question is - could you graphically flash the top main folder background when a circuit breaker pops? I've mapped out a bunch of breakers and I thought it would clever and handy to be able to see at the folder level that a breaker needs attention. Thanks - Mike

**Comment by markcellis** [comment]
I don't think this is possible. The Stream Deck SDK does not give me access to any folder navigation. It is purely managed directly by the Stream Deck application.

Mark

**Comment by MFD529** [comment]
Thanks Mark. I threw it out there not knowing what kind of magic you had in your box of tricks 🙂
________________________________

**Comment by markcellis** [comment]
Not able to do per the above conversation
