### ISSUE TITLE
Selecting An Encoder from list

### ISSUE THREAD

**Issue by Oregon47** [markcellis/X-KeyPad#58]
When selecting an encoder from the list the app takes you to the expressions list instead of the requested encoder.

**Comment by markcellis** [comment]
What version are you running? I'm pretty sure I fixed that in beta 26.

**Comment by Oregon47** [comment]
Mark, I’m running B25. How can I get 26?Bill FitzgeraldOn Apr 21, 2023, at 9:49 AM, Mark Ellis ***@***.***> wrote:﻿
What version are you running? I'm pretty sure I fixed that in beta 26.

**Comment by markcellis** [comment]
https://forums.x-plane.org/index.php?/forums/topic/284805-early-stream-deck-support-151-beta-26/&do=findComment&comment=2539993

**Comment by Oregon47** [comment]
Thx…Bill FitzgeraldOn Apr 21, 2023, at 10:14 PM, Mark Ellis ***@***.***> wrote:﻿
https://forums.x-plane.org/index.php?/forums/topic/284805-early-stream-deck-support-151-beta-26/&do=findComment&comment=2539993

**Comment by markcellis** [comment]
This was fixed in 1.5.1 Beta 26

**Comment by Oregon47** [comment]
Thanks for the link to 26B . I was not able to find this version on the Stick and Rudder website. It still has 25B linked.Bill FitzgeraldOn Apr 23, 2023, at 8:49 PM, Mark Ellis ***@***.***> wrote:﻿
Closed #58 as completed.
