### ISSUE TITLE
Editing another encoder definiton changes key definition to some kind of default key

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#59]
Let's say I'm editting key definition id 100.
Then I go to the encoder definition tab and edit the selected encoder there
Going back to the key definition tab, key 100 is still selected
Going to the encoder definition tab again, now selecting another encoder
Going back to the key definition tab... and key id 63 is selected. Always id 63.

I'd like the keys not to switch. :)

Edit: it seems to switch to the 'default' id 63 whenever I click something on the encoder definition side.

**Comment by markcellis** [comment]
This is fixed in 1.5.2 Beta 8
