### ISSUE TITLE
Imported expressive commands get 'New' prefix, even if name wasn't taken

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#61]
I believe this was fixed before, but maybe not for expressive commands. When importing commands from other profiles, there is no need to add 'New' if the name is not taken yet.

**Comment by markcellis** [comment]
I think you are correct, I'll take a look at it

**Comment by markcellis** [comment]
This is fixed and will be available in 1.5.2 Beta 9. As a side note, the problem also existed for selectively appending encoders. The only ones working properly were keys.
