### ISSUE TITLE
Request: make built in variables for expressive commands available as datarefs

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#62]
For example, `srs_number_buffer_length` is available as variable for expressive commands. It would be nice to be able to use `srs_number_buffer_length` for keys as well.

Reasoning: for the ToLiss Airbus the Barometer works differently compared to the generic ones. I'd like the single press to behave based on `srs_number_buffer_value`. If the buffer is empty, the barometer will switch to STD setting. If there something in the buffer, then it will enter that value.

I can't do this with just an expressive command, as this can only write to one target.

**Comment by markcellis** [comment]
In 1.5.2 Beta 6
