### ISSUE TITLE
Copying key assignments between virtual keypads

### ISSUE THREAD

**Issue by fwiw99** [markcellis/X-KeyPad#66]
I'm not sure if this is a bug report or an enhancement request... (I am using version 1.5.1 on XP 12)

I am trying to copy some keys from your C172 G1000 sample json to my own virtual keypad.  I therefore have two virtual devices (one of them being the sample json that I managed to import).  After some difficulty, I figured out how to use the drag/drop feature, but it only let me drag/drop within a device - it wouldn’t let me drag to a different device.  And when I tried the copy/paste option, I couldn’t get it to work at all.

There’s a button that lets me copy a given key to shift-1, but that seems to be the extent of it.  It seems to me that there must be something analogous to the key copy/paste capability I used to configure an x-touch mini.  Am I missing something?

I would add that the documentation for copy/paste for virtual keypads is kind of sparse - the only reference I could find was:

                    The Virtual Device windows have a unique ability to copy / paste keys from one unit or configuration to
                     another. It also has a Drag/Drop mode that allows you to move keys around using the mouse.

It wasn’t easy, for example, to see that I had to click on the top of keys to drag them.  I've also watched various videos without finding any answers.

Many thanks!

**Comment by fwiw99** [comment]
I meant to add that my major rationale for this request is that it would greatly facilitate the copying of keys between virtual devices with different layouts.
Thanks!

**Comment by markcellis** [comment]
This will be in 1.5.2 Beta 15

**Comment by fwiw99** [comment]
Thanks so much, Mark - this will be really useful!
Best,
Eric
