### ISSUE TITLE
 Request: Simulate Stream Deck key presses

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#67]
When creating a new profile, I don't have all the keys laid out on a Stream Deck profile yet. I first need to figure out all the datarefs and commands to get the profile working on the X-Plane side.

I need to test if my keys are working, so it would be nice to be able to simulate short/long key presses. And maybe even encoders dialing left and right.

It would fasten the development of a profile, because I wouldnd't have to add or edit every key on the Stream Deck just to test one.

Would that be possible? :)

**Comment by markcellis** [comment]
I could probably create a crude preview tab for a key and encoder. Unfortunately, the font size and color are determined when you create a key on the Stream Deck or they are specified in the layout JSON on the encoder which would be harder to emulate.

**Comment by sanderdatema** [comment]
I only want to test if the commands and datarefs work. While a preview of the encoder's screen is nice, I mainly will use it to quickly test what happens in the aircraft when I press a key. The visuals I can test later when really adding a key to the Stream Deck.
Maybe that'll make it easier?

**Comment by markcellis** [comment]
Got it. I think this would be a really useful feature.

**Comment by markcellis** [comment]
This will be available in 1.5.2 Beta 8
