### ISSUE TITLE
Generate a reference list/table of all key mappings

### ISSUE THREAD

**Issue by fwiw99** [markcellis/X-KeyPad#68]
In editing and creating virtual keypads (and other devices, for that matter), iy would be useful to have a reference list or table of key mappings (e.g. excel) w/r/t their commands and datarefs.  I can find this information in the JSON, but it is separated by many lines of parameter code.  It exists in the configuration editor, of course, but that would be tedious to paste/copy etc.

I realize that  keys can  map to multiple commands/datarefs, but I am thinking of something like:

Key______________ commands________________ datarefs
K1________________cmd1, cmd2, cmdn_________ ref1, ref2, refn
K2
...
Kn

Many thanks for consideration.

**Comment by markcellis** [comment]
This is a good idea although it can still get pretty complex.

**Comment by fwiw99** [comment]
> This is a good idea although it can still get pretty complex.

Sure.  I certainly understand if it's not worth the effort, but, as I said, it would be nice to have the reference, in the same way that I consult the XP key mapping text files.  And I certainly wouldn't expect (and probably wouldn't want the complications) to have all of the other parameters.

**Comment by markcellis** [comment]
This will be available for Stream Deck configurations in 1.5.2 Beta 9. I still need to add it for the X-Touch Mini and X-Keys configurations.

**Comment by fwiw99** [comment]
Thanks for keeping me in loop, Mark!  I use Mini and x-keypad - can't
wait.  I really appreciate this - great way to maintain a library of useful
cmds.

X-keys is a lifesaver - as much as I like VR, I find rotary dials almost
impossible to use otherwise.

Best,
Eric

**Comment by markcellis** [comment]
This is done for all editors and will be available in 1.5.2 Beta 10

**Comment by fwiw99** [comment]
Great!  many thanks.
