### ISSUE TITLE
Retain Large Unit Name Buttons Selection

### ISSUE THREAD

**Issue by ssharpe83713** [markcellis/X-KeyPad#72]
Currently, X-Keypad starts with small unit name buttons (tabs), even though the user previously selected the option for large unit name buttons.  It would be convenient to have that user option remembered so that the option doesn't have to be selected with every launch of the program.

**Comment by markcellis** [comment]
I thought it was supposed to save it. I'll take a look at it.

**Comment by markcellis** [comment]
This does persist but you need to enable it on the Virtual Device in the configuration editor. See the attached image.



![Capture](https://github.com/markcellis/X-KeyPad/assets/25938986/6cb258f3-bd9e-4edd-9ed1-3242b6c66ec0)

**Comment by ssharpe83713** [comment]
Thank you, Mark!
