### ISSUE TITLE
Change color of SAVE button when changes were made and show last save time

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#74]
I sometimes forget to press SAVE and it's gotten me into trouble a few times.

It would be nice that the moment you change something, the SAVE button turns red or something. Just to note that there are unsaved changes.

Another enhancement: to show the last autosave time (relative) in the title bar.

**Comment by markcellis** [comment]
I sent you a DM on Discord. If you have some time I'd like to talk with you about the best way to make this better.

**Comment by markcellis** [comment]
I was not able to change the color of the button as the check for changes is a bit compute-intensive and would affect the frame rate if it was done on every frame while the editor was open.

I was able to provide a warning if you close the editor and you had unsaved changes. You will also get a warning if you load a new aircraft and had unsaved changes in the previous configuration.

This will be in 1.5.2 beta 11
