### ISSUE TITLE
Make width of key index and function name fields larger

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#75]
![SCR-20240212-qedt](https://github.com/markcellis/X-KeyPad/assets/176252/5c60b0e9-8650-4ac1-bfec-ee01e07f363b)

As you can see in the screenshot: the names don't fit. Either I need to start using shorter names or maybe you can make those fields a little wider? :)

**Comment by markcellis** [comment]
I made them each 100 pixels wider.

![Capture](https://github.com/markcellis/X-KeyPad/assets/25938986/eeb4f049-7526-46b9-b056-98c0e3c1f34b)

**Comment by markcellis** [comment]
Fixed in 1.5.2 Beta 10

**Comment by sanderdatema** [comment]
Yes, that looks great.

I just realize that there are two fields now that - in the end - show the same information. In theory the text in the pull down doesn't have to be visible. It's just a way to select another key or encoder, isn't it?

**Comment by markcellis** [comment]
Yes, the drop-down lets you select it by name and the other field lets you edit the function name.

**Comment by sanderdatema** [comment]
My point is: Should the drop down show the name if the same name is shown on the field right next to it?
