### ISSUE TITLE
In File Selector sort files by date or file name

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#80]
As you can see in the screenshot, the files seem to be listed randomly. With this list it's hard to find the latest autosave.

![SCR-20240311-pfpw](https://github.com/markcellis/X-KeyPad/assets/176252/dca48203-eaae-483b-9ce6-90de0615cda1)

**Comment by markcellis** [comment]
Odd, they come back alphanumerically on Windows so I think this is an OSX and possibly Linux-only type bug. At any rate, I can get them sorted alphanumerically and may even add the ability to sort by date.

**Comment by markcellis** [comment]
This is fixed in 1.5.2 Beta 15. It will sort by file name
