### ISSUE TITLE
See if a shared dataref is already in use

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#82]
I find myself using X-KeyPad's builtin shared datarefs more and more. But apart from keeping a manual list there is no way to see which array items are in use already.

It would be nice to see which ones are taken.

**Comment by markcellis** [comment]
Have you tried the new cross reference on the File menu? it creates a tab-separated file that you can use in Excel or Google Sheets to easily see what you have used for commands and datarefs. I think I might need to add the index you are using but that is an easy add.

**Comment by markcellis** [comment]
I have added the array index to the reference name in the cross-reference. This will be in 1.5.2 beta 15. Try it and see if it meets your needs.

**Comment by markcellis** [comment]
I think this has been addressed with the cross reference feature
