### ISSUE TITLE
Not all changes are caught by 'Check for changes'

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#83]
In the two screenshots you can see that DataRefTool shows a value of around 0.5 for `laminar/B738/annunciator/apu_fire`, but Dataref Finder doesn't notice it. When 'Check for changes' is off, the value is shown correctly.

![SCR-20240312-tjqf](https://github.com/markcellis/X-KeyPad/assets/176252/eaf72497-fbb9-4bd6-a4d4-e54cc9ba027b)
![SCR-20240312-tkmk-3](https://github.com/markcellis/X-KeyPad/assets/176252/dd816511-4869-4d5a-b6ba-75804ffa1690)

**Comment by markcellis** [comment]
I can't seem to reproduce this. I tested it by modifying one of the Shared Floats using drt while X-KeyPad was looking for changes and it detected it. Can you reproduce this at will on the Zibo? If you can let me know what the steps are.

**Comment by sanderdatema** [comment]
This screencast reproduces the problem: https://link.returntosander.net/EhUGu

At first the changes are noticed. When the set time has passed (5 seconds in this example, but works with other amounts as well) the dataref is no longer checked. When deactivating and activating the check for changes, the same thing repeats.

The dataref I used: `laminar/B738/annunicator/apu_fire` which can be toggled with the TEST switch on the left site of the engine 1 DISCH switch.

**Comment by markcellis** [comment]
So this is the way it is supposed to work. Once a change is detected it will stay on the list for the persist time and then it goes away unless you lock it with the lock button. The logic is that those datarefs that are changing all the time will go away after the persist time.

Do you think there is a better way to do it?

**Comment by sanderdatema** [comment]
Well, I think the moment it changes again, it should reappear. Only if a value doesn't change for the set amount of seconds it should disappear. The DataRefTool does the same with the color changing slowly if nothing happens for a while.

**Comment by markcellis** [comment]
I sent you a DM on Discord to discuss this. I'd like to explain my logic and why it is different from DRT. Maybe we can improve on the logic.

**Comment by markcellis** [comment]
I think you are happy with the way the feature is working now.
