### ISSUE TITLE
Add Support for the Elgato StreamDeck

### ISSUE THREAD

**Issue by markcellis** [markcellis/X-KeyPad#9]
Add Support for the Elgato StreamDeck

**Comment by MFD529** [comment]
Food for thought - Would it be possible to configure the Streamdeck button to behave as an On-Off-On toggle switch? The BAe146 for example has numerous center off toggle switches. This would be the holy grail in my book ;-) Thanks - Mike D

**Comment by markcellis** [comment]
Doing it with a single key might be difficult. As an example, if the switch is in the center position and you press the key, which way do you want to go, up or down. It might be possible with the concept of a short and long press is one direction and a long press is the other direction.

 

Thoughts?

 

Mark

**Comment by MFD529** [comment]
Long & short presses would at least give a user options. I like your idea :-) Thanks

**Comment by markcellis** [comment]
This is now available in 1.5.1 Beta 17
