### ISSUE TITLE
Change copy prefix into a postfix

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#92]
When creating a copy of a key, the text `Copy of` is prefixed. It's easier to remove that text if it's a postfix, like `(copy)`.

**Comment by sanderdatema** [comment]
I just noticed Expressive Commands get no pre- or suffix at all when copying. Just a warning. And I like that, it's clean.

**Comment by markcellis** [comment]
This will be in 1.6.1 Beta 6
