### ISSUE TITLE
When editing an expression, automatic selection of pressed keys should be temporarily disabled

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#99]
If you press a key while editing another key's expression, you might get confused (at least I was) when returning from the editor as the key that was last pressed will be active and not the key whose expression you were editing.

Therefore it would be nice to temporarily deactivate that option (if it was active).

![SCR-202407151145-8xxIqJa4](https://github.com/user-attachments/assets/b4a675da-7428-43ec-b100-a93c590deef8)

**Comment by markcellis** [comment]
This will be available in 1.6.1 Beta 2
